apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: devlopment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: busybox:1.33.1
        command: ["nc", "-lkv", "-p", "8080", "-e", "/bin/sh"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: devlopment
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
  - port: 8080
    targetPort: 8080
