---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: qa
  name: qa-readers
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-reader-binding
  namespace: qa
subjects:
- kind: Group
  name: qa-readers  # Replace with the actual group name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: qa-readers
  apiGroup: rbac.authorization.k8s.io
