---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: qa  # Adjust the namespace if needed
  name: reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-binding
  namespace: qa  # Adjust the namespace if needed
subjects:
- kind: Group
  name: reader  # Replace with the actual group name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io

